server:
  port: 8899

spring:
  profiles:
    active: dev
---
spring:
  profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin123#BrijeshChauhan12
    url: jdbc:mysql://localhost:3306/ET-DEV
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
welcome:
  message: Welcome to spring world in dev

#---
#
#spring:
#  profile: qa
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: admin123#BrijeshChauhan12
#    url: jdbc:mysql://localhost:3306/ET-QA
#    username: admin
#  jpa:
#    hibernate:
#      ddl-auto: update
#welcome:
#  message: Welcome to spring world in qa

#---
#
#spring:
#  profile: prod
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: admin123#BrijeshChauhan12
#    url: jdbc:mysql://localhost:3306/ET-PROD
#    username: admin
#  jpa:
#    hibernate:
#      ddl-auto: update
#welcome:
#  message: Welcome to spring world in prod
